export const banks: Array<any> = [
    "BANAMEX",
    "BANCOMEXT",
    "BANOBRAS",
    "BBVA BANCOMER",
    "SANTANDER",
    "BANJERCITO",
    "HSBC",
    "BAJIO",
    "IXE",
    "INBURSA",
    "INTERACCIONES",
    "MIFEL",
    "SCOTIABANK",
    "BANREGIO",
    "INVEX",
    "BANSI",
    "AFIRME",
    "BANORTE",
    "THE ROYAL BANK",
    "AMERICAN EXPRESS",
    "BAMSA",
    "TOKYO",
    "JP MORGAN",
    "BMONEX",
    "VE POR MAS",
    "ING",
    "DEUTSCHE",
    "CREDIT SUISSE",
    "AZTECA",
    "AUTOFIN",
    "BARCLAYS",
    "COMPARTAMOS",
    "BANCO FAMSA",
    "BMULTIVA",
    "ACTINVER",
    "WAL-MART",
    "NAFIN",
    "INTERBANCO",
    "BANCOPPEL",
    "ABC CAPITAL",
    "UBS BANK",
    "CONSUBANCO",
    "VOLKSWAGEN",
    "CIBANCO",
    "BBASE",
    "BANSEFI",
    "HIPOTECARIA FEDERAL",
    "MONEXCB",
    "GBM",
    "MASARI",
    "VALUE",
    "ESTRUCTURADORES",
    "TIBER",
    "VECTOR",
    "B&B",
    "ACCIVAL",
    "MERRILL LYNCH",
    "FINAMEX",
    "VALMEX",
    "UNICA",
    "MAPFRE",
    "PROFUTURO",
    "CB ACTINVER",
    "OACTINVER",
    "SKANDIA",
    "CBDEUTSCHE",
    "ZURICH",
    "ZURICHVI",
    "SU CASITA",
    "CB INTERCAM",
    "CI BOLSA",
    "BULLTICK",
    "STERLING",
    "FINCOMUN",
    "HDI SEGUROS",
    "ORDER",
    "AKALA",
    "CB JPMORGAN",
    "REFORMA",
    "STP",
    "TELECOMM",
    "EVERCORE",
    "SKANDIA",
    "SEGMTY",
    "ASEA",
    "KUSPIT",
    "SOFIEXPRESS",
    "UNAGRA",
    "OPCIONES EMPRESARIALES DEL NOROESTE",
    "CLS",
    "INDEVAL",
    "LIBERTAD",
];
