interface ImportMetaEnv {
  readonly VITE_API_PATH: string
  readonly VITE_DBVAL_PRODUCT_TYPE_PP_ID: string
  readonly VITE_DBVAL_PRODUCT_TYPE_PT_ID: string
  readonly VITE_DBVAL_DEPARTMENT_PRODUCTION_ID: string
  readonly VITE_DBVAL_DEPARTMENT_COMPRAS_ID: string
  readonly VITE_DBVAL_MOVEMENT_CONCEPT_MERCHANDISE_ACQUISITION_ID: string
  readonly VITE_DBVAL_MOVEMENT_CONCEPT_PRODUCTION_OUTPUT_ID: string
  readonly VITE_DBVAL_MOVEMENT_CONCEPT_SALE_ID: string
  readonly VITE_DBVAL_MOVEMENT_CONCEPT_MERCHANDISE_RETURN_ID: string
  readonly VITE_DBVAL_MOVEMENT_CONCEPT_PRODUCTION_RECEPTION_ID: string
  readonly VITE_DBVAL_MOVEMENT_CONCEPT_EXTERNAL_SAMPLE_DELIVERY_ID: string
  readonly VITE_DBVAL_MOVEMENT_CONCEPT_HUMAN_DONATION_ID: string
  readonly VITE_DBVAL_MOVEMENT_CONCEPT_WASTE_ID: string
  readonly VITE_DBVAL_MOVEMENT_CONCEPT_FORAGE_LIVESTOCK_ID: string
  readonly VITE_DBVAL_MOVEMENT_TYPE_ENTRY_AUTHORIZATION_ID: string
  readonly VITE_DBVAL_MOVEMENT_TYPE_EXIT_VOUCHER_ID: string
}