export const movementTypeMapping = {
  [import.meta.env.VITE_DBVAL_MOVEMENT_CONCEPT_MERCHANDISE_ACQUISITION_ID]:
    import.meta.env.VITE_DBVAL_MOVEMENT_TYPE_ENTRY_AUTHORIZATION_ID,
  [import.meta.env.VITE_DBVAL_MOVEMENT_CONCEPT_PRODUCTION_OUTPUT_ID]:
    import.meta.env.VITE_DBVAL_MOVEMENT_TYPE_EXIT_VOUCHER_ID,
  [import.meta.env.VITE_DBVAL_MOVEMENT_CONCEPT_SALE_ID]: import.meta.env
    .VITE_DBVAL_MOVEMENT_TYPE_EXIT_AUTHORIZATION_ID,
  [import.meta.env.VITE_DBVAL_MOVEMENT_CONCEPT_MERCHANDISE_RETURN_ID]:
    import.meta.env.VITE_DBVAL_MOVEMENT_TYPE_ENTRY_AUTHORIZATION_ID,
  [import.meta.env.VITE_DBVAL_MOVEMENT_CONCEPT_PRODUCTION_RECEPTION_ID]:
    import.meta.env.VITE_DBVAL_MOVEMENT_TYPE_ENTRY_VOUCHER_ID,
  [import.meta.env.VITE_DBVAL_MOVEMENT_CONCEPT_EXTERNAL_SAMPLE_DELIVERY_ID]:
    import.meta.env.VITE_DBVAL_MOVEMENT_TYPE_EXIT_AUTHORIZATION_ID,
  [import.meta.env.VITE_DBVAL_MOVEMENT_CONCEPT_HUMAN_DONATION_ID]: import.meta
    .env.VITE_DBVAL_MOVEMENT_TYPE_EXIT_AUTHORIZATION_ID,
  [import.meta.env.VITE_DBVAL_MOVEMENT_CONCEPT_WASTE_ID]: import.meta.env
    .VITE_DBVAL_MOVEMENT_TYPE_EXIT_AUTHORIZATION_ID,
  [import.meta.env.VITE_DBVAL_MOVEMENT_CONCEPT_FORAGE_LIVESTOCK_ID]: import.meta
    .env.VITE_DBVAL_MOVEMENT_TYPE_EXIT_AUTHORIZATION_ID,
};

export const section2ModeMapping = {
  [import.meta.env.VITE_DBVAL_MOVEMENT_TYPE_ENTRY_AUTHORIZATION_ID]: "entry",
  [import.meta.env.VITE_DBVAL_MOVEMENT_TYPE_EXIT_VOUCHER_ID]: "exit",
};
